version: '3'
services:
  # 网关
  nginx:
    image: nginx:1.17.6-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # 映射 nginx 配置文件
      - ./logs/nginx:/var/log/nginx # 日志文件
    ports:
      - 9000:80 # 宿主端口:容器端口
    links:
      - frontend
      - backend

  # 前端
  frontend:
    image: axetroy/wsm-frontend:1.0.0
    restart: always
    links:
      - backend
    environment:
      - PORT=80
      - HOST=0.0.0.0

  # 后端接口
  backend:
    image: axetroy/wsm-backend:1.0.0
    restart: always
    volumes:
      - "./.env:/app/bin/.env"
    environment:
      - USER_HTTP_PORT=80
      - DB_HOST=192.168.3.15 # 改成机器的 IP 或者域名
      - DB_PORT=54321