# Copyright 2019-2020 Axetroy. All rights reserved. Apache License 2.0.
version: "3"
services:
  # 网关
  nginx:
    image: nginx:1.20.0-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 8000:80 # 宿主端口:容器端口
    links:
      - frontend
      - backend

  # 前端
  frontend:
    image: axetroy/wsm-frontend:latest
    restart: always
    links:
      - backend
    environment:
      - API_HOST=http://192.168.1.29:9000 # 请求接口的域名, 请自行更改

  # 后端接口
  backend:
    image: axetroy/wsm-backend:latest
    restart: always
    ports:
      - 9000:80
    environment:
      # 更多环境变量配置请查看 .env 文件
      - DB_HOST=192.168.1.29 # 要连接的数据库 IP，请自行更改
      - DB_PORT=54321 # 要连接的数据库端口