name: backend

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        go: ['1.14.2']
        os: [ubuntu-latest]
    name: Go ${{ matrix.go }} test in ${{ matrix.os }}

    services:
      postgres:
        image: postgres:9.6.16
        env:
          POSTGRES_USER: terminal
          POSTGRES_PASSWORD: terminal
          POSTGRES_DB: terminal
        ports:
          - 54321:5432
        # needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env
      - name: Test
        run: make test

      - name: Build
        run: make build-backend

      # after success
      #      - name: Coverage
      #        if: startsWith(matrix.os, 'ubuntu')
      #        run: |
      #          go get golang.org/x/tools/cmd/cover
      #          go get github.com/mattn/goveralls
      #          /home/runner/go/bin/goveralls -coverprofile=coverage.out -service=github-action -repotoken ${{ secrets.COVERALLS_TOKEN }}

  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/wsm'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            bin/wsm_darwin_amd64.tar.gz
            bin/wsm_linux_amd64.tar.gz
            bin/wsm_windows_amd64.tar.gz
          draft: false