name: frontend

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        node: ['v12.13.0']
        os: [ubuntu-latest]
    name: Node.js ${{ matrix.node }} test in ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Dependency
        working-directory: ./frontend
        run: yarn

      - name: Build
        working-directory: ./frontend
        run: npm run build